/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/gardens": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create
         * @description Create a garden. The token comes back here and is the only way back in.
         */
        post: operations["create_api_v1_gardens_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/gardens/{token}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read */
        get: operations["read_api_v1_gardens__token__get"];
        put?: never;
        post?: never;
        /** Remove */
        delete: operations["remove_api_v1_gardens__token__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/gardens/{token}/beds": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Bed
         * @description Add a bed and compute its light immediately.
         *
         *     PolygonError, SoilTypeError and MoistureError all subclass ValueError, so they
         *     surface as 422 with their reason rather than as a 500.
         *
         *     `add_bed` computes the light itself, so the invariant does not depend on which
         *     entry point created the bed — it used to live here, and a bed made through the
         *     store had no light at all.
         */
        post: operations["create_bed_api_v1_gardens__token__beds_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/gardens/{token}/beds/{bed_id}/plantings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Planting
         * @description Put a species in a bed. An unknown taxon raises ValueError -> 422.
         */
        post: operations["create_planting_api_v1_gardens__token__beds__bed_id__plantings_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/gardens/{token}/beds/{bed_id}/suggestions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Bed Suggestions
         * @description Species that suit this bed, ranked by fit against its own site vector.
         *
         *     The bed's derived axes are the query, so the user never types an Ellenberg
         *     number. Trees and shrubs are excluded by default: a bed is a few square
         *     metres, and a hemlock that fits the light perfectly is still a useless
         *     suggestion. Introduced species are excluded for a different reason: the
         *     product promises native plants, and a third of the catalogue is not.
         */
        get: operations["bed_suggestions_api_v1_gardens__token__beds__bed_id__suggestions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/gardens/{token}/improvements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Improvements
         * @description What to plant, and what it would gain.
         *
         *     Additions come first because they are the safer advice: a swap removes
         *     something, and the score will recommend removing a valuable plant whose month
         *     is already saturated. See the known issue in 19-swap-suggestions.
         */
        get: operations["improvements_api_v1_gardens__token__improvements_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/gardens/{token}/obstacles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Obstacle
         * @description Add an obstacle and recompute in the same call.
         *
         *     Requiring a second request would leave the plan showing light values that no
         *     longer match its own obstacles — and nothing would make that visible.
         */
        post: operations["create_obstacle_api_v1_gardens__token__obstacles_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/gardens/{token}/plantings/{planting_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Planting
         * @description Remove a planting. Reached through its garden, never by a bare id.
         */
        delete: operations["delete_planting_api_v1_gardens__token__plantings__planting_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/gardens/{token}/recompute": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Recompute */
        post: operations["recompute_api_v1_gardens__token__recompute_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/gardens/{token}/score": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Score
         * @description What this planting is worth to insects, with its components.
         */
        get: operations["score_api_v1_gardens__token__score_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/gardens/{token}/timeline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Timeline
         * @description The garden's bloom year, month by month, with gaps marked.
         *
         *     `forage=true` (the default) weights each flowering planting by its counted
         *     German insect partners, so a month of nectarless cultivars is correctly a
         *     gap. `forage=false` counts every planting equally, for planning by looks.
         */
        get: operations["timeline_api_v1_gardens__token__timeline_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/plants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search Plants
         * @description Species ranked by how well they fit the given site conditions.
         */
        get: operations["search_plants_api_v1_plants_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/plants/{taxon_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Plant Detail
         * @description One species, every trait with the source behind it.
         */
        get: operations["plant_detail_api_v1_plants__taxon_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Healthz
         * @description Liveness probe for the deploy cron and the reverse proxy.
         *
         *     Deliberately dependency-free: it must answer while the app is otherwise
         *     broken, or a failing deploy looks identical to a failing database.
         */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AxisFitOut
         * @description Why one axis scored what it did — Wave 4 renders the band, not the number.
         */
        AxisFitOut: {
            /** Band */
            band: string;
            /** Half Widths Away */
            half_widths_away: number;
            /** Niche Width */
            niche_width: number;
            /** Score */
            score: number;
            /** Species Value */
            species_value: number;
            /** Width Estimated */
            width_estimated: boolean;
        };
        /** BedCreate */
        BedCreate: {
            /** Moisture */
            moisture?: string | null;
            /** Name */
            name: string;
            /** Polygon */
            polygon: number[][];
            /** Soil Type */
            soil_type?: string | null;
        };
        /** BedOut */
        BedOut: {
            /** Bed Id */
            bed_id: number;
            /** Ellenberg L */
            ellenberg_l: number | null;
            /** Ellenberg M */
            ellenberg_m: number | null;
            /** Ellenberg N */
            ellenberg_n: number | null;
            /** Ellenberg R */
            ellenberg_r: number | null;
            /** Light Computed At */
            light_computed_at: string | null;
            /** Moisture */
            moisture: string | null;
            /** Name */
            name: string;
            /** Plantings */
            plantings: components["schemas"]["PlantingOut"][];
            /** Polygon */
            polygon: number[][];
            /** Soil Type */
            soil_type: string | null;
            /** Sun Hours */
            sun_hours: number | null;
        };
        /**
         * BedSuggestions
         * @description Suggestions for one bed, with the site vector they were ranked against —
         *     so the UI can say what it matched on rather than showing a bare list.
         */
        BedSuggestions: {
            /** Bed Id */
            bed_id: number;
            /** Bed Name */
            bed_name: string;
            /** Items */
            items: components["schemas"]["PlantSummary"][];
            /** Site Axes */
            site_axes: {
                [key: string]: number;
            };
            /** Total */
            total: number;
        };
        /** ChangeOut */
        ChangeOut: {
            /** Bed Id */
            bed_id: number;
            /** Bed Name */
            bed_name: string;
            /** Canonical Name */
            canonical_name: string;
            /** Gain */
            gain: number;
            /** German Partners */
            german_partners: number | null;
            /** Reason */
            reason: string;
            /** Replaces Name */
            replaces_name: string | null;
            /** Replaces Planting Id */
            replaces_planting_id: number | null;
            /** Resulting Score */
            resulting_score: number;
            /** Taxon Id */
            taxon_id: number;
        };
        /** FitOut */
        FitOut: {
            /** Axes */
            axes: {
                [key: string]: components["schemas"]["AxisFitOut"];
            };
            /** Score */
            score: number;
        };
        /** GapOut */
        GapOut: {
            /** Length */
            length: number;
            /** Months */
            months: number[];
        };
        /**
         * GardenCreate
         * @description Creating a garden. Latitude and longitude are range-checked here, before
         *     they reach solar code that would happily compute a sun path for latitude 500.
         */
        GardenCreate: {
            /** Latitude */
            latitude: number;
            /** Longitude */
            longitude: number;
            /** Name */
            name: string;
        };
        /**
         * GardenCreated
         * @description The token is returned; the numeric id deliberately is not.
         */
        GardenCreated: {
            /** Name */
            name: string;
            /** Share Token */
            share_token: string;
        };
        /** GardenOut */
        GardenOut: {
            /** Beds */
            beds: components["schemas"]["BedOut"][];
            /** Created At */
            created_at: string;
            /** Latitude */
            latitude: number;
            /** Longitude */
            longitude: number;
            /** Name */
            name: string;
            /** Obstacles */
            obstacles: components["schemas"]["ObstacleOut"][];
            /** Share Token */
            share_token: string;
            /** Updated At */
            updated_at: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ImprovementsOut */
        ImprovementsOut: {
            /** Additions */
            additions: components["schemas"]["ChangeOut"][];
            /** Current Score */
            current_score: number;
            /** Swaps */
            swaps: components["schemas"]["ChangeOut"][];
        };
        /** MonthOut */
        MonthOut: {
            /** Coverage */
            coverage: number;
            /** Month */
            month: number;
            /** Species */
            species: string[];
        };
        /** ObstacleCreate */
        ObstacleCreate: {
            /** Height */
            height: number;
            /** Kind */
            kind: string;
            /** Radius */
            radius: number;
            /** X */
            x: number;
            /** Y */
            y: number;
        };
        /** ObstacleOut */
        ObstacleOut: {
            /** Height */
            height: number;
            /** Kind */
            kind: string;
            /** Obstacle Id */
            obstacle_id: number;
            /** Radius */
            radius: number;
            /** X */
            x: number;
            /** Y */
            y: number;
        };
        /** PartnersOut */
        PartnersOut: {
            /** By Kind */
            by_kind: {
                [key: string]: number;
            };
            /** German */
            german: number;
            /** Global Total */
            global_total: number;
            /** Match Rate */
            match_rate: number;
            /** Unmatched */
            unmatched: number;
        };
        /** PlantDetail */
        PlantDetail: {
            /** Canonical Name */
            canonical_name: string;
            /** Family */
            family: string | null;
            partners: components["schemas"]["PartnersOut"] | null;
            /** Scientific Name */
            scientific_name: string | null;
            /** Taxon Id */
            taxon_id: number;
            /** Traits */
            traits: {
                [key: string]: components["schemas"]["TraitOut"];
            };
        };
        /** PlantSearchResponse */
        PlantSearchResponse: {
            /** Items */
            items: components["schemas"]["PlantSummary"][];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Total */
            total: number;
        };
        /** PlantSummary */
        PlantSummary: {
            /** Canonical Name */
            canonical_name: string;
            /** Colour Known */
            colour_known: boolean;
            /** Family */
            family: string | null;
            fit: components["schemas"]["FitOut"];
            /** Flower Colour */
            flower_colour: string | null;
            /** Flowering End Month */
            flowering_end_month: number | null;
            /** Flowering Start Month */
            flowering_start_month: number | null;
            /** Height Max M */
            height_max_m: number | null;
            /** Taxon Id */
            taxon_id: number;
        };
        /** PlantingCreate */
        PlantingCreate: {
            /**
             * Quantity
             * @default 1
             */
            quantity: number;
            /** Taxon Id */
            taxon_id: number;
        };
        /** PlantingOut */
        PlantingOut: {
            /** Added At */
            added_at: string;
            /** Canonical Name */
            canonical_name: string;
            /** Planting Id */
            planting_id: number;
            /** Quantity */
            quantity: number;
            /** Taxon Id */
            taxon_id: number;
        };
        /**
         * ScoreOut
         * @description The score with everything needed to argue about it — a score a user cannot
         *     interrogate is decoration, and this one will be trusted more than it deserves.
         */
        ScoreOut: {
            /** By Group */
            by_group: {
                [key: string]: number;
            };
            /** By Month */
            by_month: {
                [key: string]: number;
            };
            /** By Species */
            by_species: components["schemas"]["SpeciesContributionOut"][];
            /** Is Empty */
            is_empty: boolean;
            /** Plantings Total */
            plantings_total: number;
            /** Plantings Without Interaction Data */
            plantings_without_interaction_data: number;
            /** Score */
            score: number;
        };
        /** SpeciesContributionOut */
        SpeciesContributionOut: {
            /** Canonical Name */
            canonical_name: string;
            /** Forage */
            forage: number;
            /** German Partners */
            german_partners: number | null;
            /** Months */
            months: number[];
            /** Origin */
            origin: string;
            /** Taxon Id */
            taxon_id: number;
        };
        /**
         * TimelineOut
         * @description The bloom year. `plantings_without_interaction_data` is reported so a
         *     timeline built mostly on unknowns is visible rather than merely optimistic.
         */
        TimelineOut: {
            /** Gaps */
            gaps: components["schemas"]["GapOut"][];
            /** Is Empty */
            is_empty: boolean;
            /** Mode */
            mode: string;
            /** Months */
            months: components["schemas"]["MonthOut"][];
            /** Plantings Total */
            plantings_total: number;
            /** Plantings Without Interaction Data */
            plantings_without_interaction_data: number;
        };
        /** TraitOut */
        TraitOut: {
            /** Alternatives */
            alternatives?: {
                [key: string]: unknown;
            }[];
            /** License */
            license: string;
            /** Source */
            source: string;
            /** Unit */
            unit?: string | null;
            /** Value */
            value: number | string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    create_api_v1_gardens_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GardenCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GardenCreated"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_api_v1_gardens__token__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GardenOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_api_v1_gardens__token__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_bed_api_v1_gardens__token__beds_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BedCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GardenOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_planting_api_v1_gardens__token__beds__bed_id__plantings_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
                bed_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlantingCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GardenOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    bed_suggestions_api_v1_gardens__token__beds__bed_id__suggestions_get: {
        parameters: {
            query?: {
                limit?: number;
                colour?: string | null;
                include_trees?: boolean;
                include_introduced?: boolean;
                exclude_planted?: boolean;
            };
            header?: never;
            path: {
                token: string;
                bed_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BedSuggestions"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    improvements_api_v1_gardens__token__improvements_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImprovementsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_obstacle_api_v1_gardens__token__obstacles_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ObstacleCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GardenOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_planting_api_v1_gardens__token__plantings__planting_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
                planting_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GardenOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    recompute_api_v1_gardens__token__recompute_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GardenOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    score_api_v1_gardens__token__score_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScoreOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    timeline_api_v1_gardens__token__timeline_get: {
        parameters: {
            query?: {
                forage?: boolean;
            };
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TimelineOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_plants_api_v1_plants_get: {
        parameters: {
            query?: {
                light?: number | null;
                moisture?: number | null;
                nutrients?: number | null;
                reaction?: number | null;
                temperature?: number | null;
                height_min?: number | null;
                height_max?: number | null;
                flowering_month?: number | null;
                colour?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlantSearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    plant_detail_api_v1_plants__taxon_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                taxon_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlantDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
