/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/plants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search Plants
         * @description Species ranked by how well they fit the given site conditions.
         */
        get: operations["search_plants_api_v1_plants_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/plants/{taxon_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Plant Detail
         * @description One species, every trait with the source behind it.
         */
        get: operations["plant_detail_api_v1_plants__taxon_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/plants/{taxon_id}/info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Plant Info
         * @description A description and photograph, from Wikipedia, cached on this deployment.
         *
         *     404 when no article exists in either language — an honest absence rather than
         *     an empty panel that looks like a loading failure.
         */
        get: operations["plant_info_api_v1_plants__taxon_id__info_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stats
         * @description The catalogue in numbers, for the page that introduces it.
         */
        get: operations["stats_api_v1_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/gardens": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create
         * @description Create a garden. The token comes back here and is the only way back in.
         */
        post: operations["create_api_v1_gardens_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/gardens/{token}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read */
        get: operations["read_api_v1_gardens__token__get"];
        put?: never;
        post?: never;
        /** Remove */
        delete: operations["remove_api_v1_gardens__token__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/gardens/{token}/beds": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Bed
         * @description Add a bed and compute its light immediately.
         *
         *     PolygonError, SoilTypeError and MoistureError all subclass ValueError, so they
         *     surface as 422 with their reason rather than as a 500.
         *
         *     `add_bed` computes the light itself, so the invariant does not depend on which
         *     entry point created the bed — it used to live here, and a bed made through the
         *     store had no light at all.
         */
        post: operations["create_bed_api_v1_gardens__token__beds_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/gardens/{token}/obstacles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Obstacle
         * @description Add an obstacle and recompute in the same call.
         *
         *     Requiring a second request would leave the plan showing light values that no
         *     longer match its own obstacles — and nothing would make that visible.
         */
        post: operations["create_obstacle_api_v1_gardens__token__obstacles_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/gardens/{token}/recompute": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Recompute */
        post: operations["recompute_api_v1_gardens__token__recompute_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/gardens/{token}/beds/{bed_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Edit Bed
         * @description Change what a bed is. Raising it changes its light, so the light is redone.
         *
         *     Leaving the stored number alone would leave the screen describing a bed that
         *     no longer exists — the same reason adding an obstacle recomputes.
         */
        patch: operations["edit_bed_api_v1_gardens__token__beds__bed_id__patch"];
        trace?: never;
    };
    "/api/v1/gardens/{token}/obstacles/{obstacle_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Edit Obstacle
         * @description Change what an obstacle is, and redo every bed's light.
         */
        patch: operations["edit_obstacle_api_v1_gardens__token__obstacles__obstacle_id__patch"];
        trace?: never;
    };
    "/api/v1/gardens/{token}/claim": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Claim
         * @description Put a garden under an account.
         *
         *     Holding the link is enough to edit a garden — that was Wave 3's bargain and
         *     it stays — but not enough to take it from whoever claimed it. Share links go
         *     on working afterwards: removing them to push registration would be a
         *     downgrade dressed as a feature.
         */
        post: operations["claim_api_v1_gardens__token__claim_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/gardens/{token}/beds/{bed_id}/plantings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Planting
         * @description Put a plant in a bed, named by id or by the words the user typed.
         *
         *     A name that resolves to exactly one species is stored with that species and
         *     counts like any other planting. One that does not is stored anyway, marked
         *     unidentified: discarding it would tell someone their garden is wrong because
         *     our catalogue is incomplete.
         */
        post: operations["create_planting_api_v1_gardens__token__beds__bed_id__plantings_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/gardens/{token}/plantings/{planting_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Planting
         * @description Remove a planting. Reached through its garden, never by a bare id.
         */
        delete: operations["delete_planting_api_v1_gardens__token__plantings__planting_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/gardens/{token}/beds/{bed_id}/suggestions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Bed Suggestions
         * @description Species that suit this bed, ranked by fit against its own site vector.
         *
         *     The bed's derived axes are the query, so the user never types an Ellenberg
         *     number. Trees and shrubs are excluded by default: a bed is a few square
         *     metres, and a hemlock that fits the light perfectly is still a useless
         *     suggestion. Introduced species are excluded for a different reason: the
         *     product promises native plants, and a third of the catalogue is not.
         */
        get: operations["bed_suggestions_api_v1_gardens__token__beds__bed_id__suggestions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/gardens/{token}/timeline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Timeline
         * @description The garden's bloom year, month by month, with gaps marked.
         *
         *     `forage=true` (the default) weights each flowering planting by its counted
         *     German insect partners, so a month of nectarless cultivars is correctly a
         *     gap. `forage=false` counts every planting equally, for planning by looks.
         */
        get: operations["timeline_api_v1_gardens__token__timeline_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/gardens/{token}/score": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Score
         * @description What this planting is worth to insects, with its components.
         */
        get: operations["score_api_v1_gardens__token__score_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/gardens/{token}/improvements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Improvements
         * @description What to plant, and what it would gain.
         *
         *     Additions come first because they are the safer advice: a swap removes
         *     something, and the score will recommend removing a valuable plant whose month
         *     is already saturated. See the known issue in 19-swap-suggestions.
         */
        get: operations["improvements_api_v1_gardens__token__improvements_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/gardens/{token}/bloom": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Bloom
         * @description Which colours each bed carries in each month.
         *
         *     Server-side because the frontend has a bed's plantings but neither their
         *     flowering windows nor their colours, and sending those per planting would
         *     ship the catalogue to the browser to render a swatch.
         */
        get: operations["bloom_api_v1_gardens__token__bloom_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/gardens/{token}/sightlines": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sightlines
         * @description What is visible from a point in the garden.
         *
         *     The same cylinders the shading model uses, seen from an eye instead of from
         *     the sun — so a hedge blocks sight exactly as it blocks light, and a raised
         *     bed stands above both.
         */
        post: operations["sightlines_api_v1_gardens__token__sightlines_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/geo/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Find Place
         * @description Addresses matching a query. Empty in, empty out — a keystroke-per-request
         *     search would be a poor way to treat a free community service.
         */
        get: operations["find_place_api_v1_geo_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/geo/imagery": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Imagery At
         * @description Which state's orthophotos may be shown here, if any.
         *
         *     Per Bundesland because the licences are: there is no federal source, and a
         *     state without an entry gets no imagery rather than a neighbour's.
         */
        get: operations["imagery_at_api_v1_geo_imagery_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/gardens/from-map": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Garden From Map
         * @description Create a garden from an outline drawn on the map, with what shades it.
         *
         *     The margin is 50 m and objects are filtered by whether their shadow could
         *     arrive at all — generous where it matters, quiet where it does not.
         */
        post: operations["garden_from_map_api_v1_gardens_from_map_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register
         * @description Create an account. Email is optional and the cost of that is returned.
         */
        post: operations["register_api_v1_accounts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Log In
         * @description Log in. A wrong password and an unknown user answer identically.
         */
        post: operations["log_in_api_v1_sessions_post"];
        /** Log Out */
        delete: operations["log_out_api_v1_sessions_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/accounts/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_v1_accounts_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/accounts/me/gardens": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * My Gardens
         * @description The gardens this account has claimed.
         *
         *     A place to keep the links, not a replacement for them: the share token is
         *     still what opens a garden, and it comes back here so the list can.
         */
        get: operations["my_gardens_api_v1_accounts_me_gardens_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Healthz
         * @description Liveness probe for the deploy cron and the reverse proxy.
         *
         *     Deliberately dependency-free: it must answer while the app is otherwise
         *     broken, or a failing deploy looks identical to a failing database.
         */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AccountOut
         * @description Never carries the password or the hash — there is no field for either.
         */
        AccountOut: {
            /** Username */
            username: string;
            /** Email */
            email: string | null;
            /** Recovery Note */
            recovery_note: string;
        };
        /**
         * AxisFitOut
         * @description Why one axis scored what it did — Wave 4 renders the band, not the number.
         */
        AxisFitOut: {
            /** Band */
            band: string;
            /** Score */
            score: number;
            /** Half Widths Away */
            half_widths_away: number;
            /** Species Value */
            species_value: number;
            /** Niche Width */
            niche_width: number;
            /** Width Estimated */
            width_estimated: boolean;
        };
        /** BedCreate */
        BedCreate: {
            /** Name */
            name: string;
            /** Polygon */
            polygon: number[][];
            /** Soil Type */
            soil_type?: string | null;
            /** Moisture */
            moisture?: string | null;
        };
        /** BedMonthColours */
        BedMonthColours: {
            /** Month */
            month: number;
            /** Colours */
            colours: string[];
            /** Unknown */
            unknown: number;
            /** Flowering */
            flowering: number;
        };
        /** BedOut */
        BedOut: {
            /** Bed Id */
            bed_id: number;
            /** Name */
            name: string;
            /** Polygon */
            polygon: number[][];
            /** Soil Type */
            soil_type: string | null;
            /** Moisture */
            moisture: string | null;
            /** Ellenberg L */
            ellenberg_l: number | null;
            /** Ellenberg M */
            ellenberg_m: number | null;
            /** Ellenberg N */
            ellenberg_n: number | null;
            /** Ellenberg R */
            ellenberg_r: number | null;
            /** Sun Hours */
            sun_hours: number | null;
            /** Light Computed At */
            light_computed_at: string | null;
            /** Height Above Ground */
            height_above_ground: number;
            /** Label */
            label: string | null;
            /** Plantings */
            plantings: components["schemas"]["PlantingOut"][];
        };
        /** BedPalette */
        BedPalette: {
            /** Bed Id */
            bed_id: number;
            /** Months */
            months: components["schemas"]["BedMonthColours"][];
        };
        /**
         * BedSuggestions
         * @description Suggestions for one bed, with the site vector they were ranked against —
         *     so the UI can say what it matched on rather than showing a bare list.
         */
        BedSuggestions: {
            /** Bed Id */
            bed_id: number;
            /** Bed Name */
            bed_name: string;
            /** Site Axes */
            site_axes: {
                [key: string]: number;
            };
            /** Total */
            total: number;
            /** Items */
            items: components["schemas"]["PlantSummary"][];
            /**
             * Woody
             * @default []
             */
            woody: components["schemas"]["PlantSummary"][];
            /**
             * Woody Total
             * @default 0
             */
            woody_total: number;
            /**
             * Filters
             * @default {}
             */
            filters: {
                [key: string]: components["schemas"]["FilterCountsOut"];
            };
        };
        /** BedUpdate */
        BedUpdate: {
            /** Name */
            name?: string | null;
            /** Soil Type */
            soil_type?: string | null;
            /** Moisture */
            moisture?: string | null;
            /** Height Above Ground */
            height_above_ground?: number | null;
            /** Label */
            label?: string | null;
        };
        /** BloomPalette */
        BloomPalette: {
            /** Beds */
            beds: components["schemas"]["BedPalette"][];
        };
        /** ChangeOut */
        ChangeOut: {
            /** Taxon Id */
            taxon_id: number;
            /** Canonical Name */
            canonical_name: string;
            /** Bed Id */
            bed_id: number;
            /** Bed Name */
            bed_name: string;
            /** Gain */
            gain: number;
            /** Resulting Score */
            resulting_score: number;
            /** Reason */
            reason: string;
            /** German Partners */
            german_partners: number | null;
            /** Replaces Planting Id */
            replaces_planting_id: number | null;
            /** Replaces Name */
            replaces_name: string | null;
        };
        /** Credentials */
        Credentials: {
            /** Username */
            username: string;
            /** Password */
            password: string;
        };
        /**
         * FilterCountsOut
         * @description How one active filter divided the candidate set.
         *
         *     Reported so the UI can say what was left out. `unknown` is not a rounding
         *     error: height is recorded for 44% of German species and colour for 6.6%, and
         *     a filter that hides that is indistinguishable from one that is broken.
         */
        FilterCountsOut: {
            /** Matched */
            matched: number;
            /** Unknown */
            unknown: number;
            /** Excluded */
            excluded: number;
        };
        /** FitOut */
        FitOut: {
            /** Score */
            score: number;
            /** Axes */
            axes: {
                [key: string]: components["schemas"]["AxisFitOut"];
            };
        };
        /** GapOut */
        GapOut: {
            /** Months */
            months: number[];
            /** Length */
            length: number;
        };
        /**
         * GardenCreate
         * @description Creating a garden. Latitude and longitude are range-checked here, before
         *     they reach solar code that would happily compute a sun path for latitude 500.
         */
        GardenCreate: {
            /** Name */
            name: string;
            /** Latitude */
            latitude: number;
            /** Longitude */
            longitude: number;
        };
        /**
         * GardenCreated
         * @description The token is returned; the numeric id deliberately is not.
         */
        GardenCreated: {
            /** Share Token */
            share_token: string;
            /** Name */
            name: string;
        };
        /** GardenOut */
        GardenOut: {
            /**
             * Unidentified Plantings
             * @default 0
             */
            unidentified_plantings: number;
            /** Share Token */
            share_token: string;
            /** Name */
            name: string;
            /** Latitude */
            latitude: number;
            /** Longitude */
            longitude: number;
            /** Created At */
            created_at: string;
            /** Updated At */
            updated_at: string;
            /** Beds */
            beds: components["schemas"]["BedOut"][];
            /** Obstacles */
            obstacles: components["schemas"]["ObstacleOut"][];
        };
        /**
         * GrowthForm
         * @description The growth forms the catalogue actually records.
         *
         *     A closed set rather than a free string. The value never reaches SQL, but an
         *     unbounded parameter that silently matches nothing is its own kind of lie —
         *     the user cannot tell a typo from an empty catalogue.
         * @enum {string}
         */
        GrowthForm: "forb" | "herb" | "graminoid" | "shrub" | "subshrub" | "tree";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HeightReport
         * @description Where the heights around this garden came from.
         *
         *     Reported because an assumed height presented as a measured one is the same
         *     lie as a filter that hides what it dropped.
         */
        HeightReport: {
            /** Measured */
            measured: number;
            /** Estimated */
            estimated: number;
            /** Assumed */
            assumed: number;
        };
        /**
         * ImageryOut
         * @description The aerial imagery available at a place, if any.
         *
         *     `attribution` is a condition of the licence, not a caption — DL-DE/BY-2.0
         *     and CC-BY-4.0 both require the named credit, so imagery shown without it is
         *     imagery used outside its terms.
         */
        ImageryOut: {
            /** Available */
            available: boolean;
            /** State */
            state?: string | null;
            /** Url */
            url?: string | null;
            /** Layer */
            layer?: string | null;
            /** Licence */
            licence?: string | null;
            /** Attribution */
            attribution?: string | null;
        };
        /** ImprovementsOut */
        ImprovementsOut: {
            /** Current Score */
            current_score: number;
            /** Additions */
            additions: components["schemas"]["ChangeOut"][];
            /** Swaps */
            swaps: components["schemas"]["ChangeOut"][];
        };
        /** LatLonIn */
        LatLonIn: {
            /** Lat */
            lat: number;
            /** Lon */
            lon: number;
        };
        /**
         * MapGardenOut
         * @description A garden created from the map, and what the map could and could not say.
         */
        MapGardenOut: {
            garden: components["schemas"]["GardenOut"];
            heights: components["schemas"]["HeightReport"];
        };
        /** MapSelection */
        MapSelection: {
            /** Name */
            name: string;
            /** Outline */
            outline: components["schemas"]["LatLonIn"][];
            /**
             * Neighbourhood
             * @default detached
             */
            neighbourhood: string;
        };
        /** MonthOut */
        MonthOut: {
            /** Month */
            month: number;
            /** Coverage */
            coverage: number;
            /** Species */
            species: string[];
        };
        /**
         * ObjectKind
         * @description The things a gardener points at and names.
         *
         *     Stored as text, so a renamed member orphans every saved row — the values are
         *     part of the data, not an implementation detail.
         * @enum {string}
         */
        ObjectKind: "tree" | "hedge" | "shrub" | "building" | "wall" | "fence" | "other";
        /** ObstacleCreate */
        ObstacleCreate: {
            kind: components["schemas"]["ObjectKind"];
            /** X */
            x: number;
            /** Y */
            y: number;
            /** Radius */
            radius: number;
            /** Height */
            height: number;
            /** Label */
            label?: string | null;
        };
        /** ObstacleOut */
        ObstacleOut: {
            /** Obstacle Id */
            obstacle_id: number;
            /** Kind */
            kind: string;
            /** Label */
            label: string | null;
            /** Height Source */
            height_source: string;
            /** X */
            x: number;
            /** Y */
            y: number;
            /** Radius */
            radius: number;
            /** Height */
            height: number;
        };
        /**
         * ObstacleUpdate
         * @description Every field optional: an edit says what changed, not what everything is.
         */
        ObstacleUpdate: {
            kind?: components["schemas"]["ObjectKind"] | null;
            /** X */
            x?: number | null;
            /** Y */
            y?: number | null;
            /** Radius */
            radius?: number | null;
            /** Height */
            height?: number | null;
            /** Label */
            label?: string | null;
            /** Height Source */
            height_source?: string | null;
        };
        /** OwnedGarden */
        OwnedGarden: {
            /** Name */
            name: string;
            /** Share Token */
            share_token: string;
            /** Updated At */
            updated_at: string;
        };
        /** OwnedGardens */
        OwnedGardens: {
            /** Gardens */
            gardens: components["schemas"]["OwnedGarden"][];
        };
        /** PartnersOut */
        PartnersOut: {
            /** German */
            german: number;
            /** Global Total */
            global_total: number;
            /** Unmatched */
            unmatched: number;
            /** Match Rate */
            match_rate: number;
            /** By Kind */
            by_kind: {
                [key: string]: number;
            };
            /**
             * Birds
             * @default 0
             */
            birds: number;
        };
        /** PlaceOut */
        PlaceOut: {
            /** Name */
            name: string;
            /** Lat */
            lat: number;
            /** Lon */
            lon: number;
        };
        /** PlaceSearchOut */
        PlaceSearchOut: {
            /** Places */
            places: components["schemas"]["PlaceOut"][];
        };
        /** PlantDetail */
        PlantDetail: {
            /** Taxon Id */
            taxon_id: number;
            /** Canonical Name */
            canonical_name: string;
            /** Scientific Name */
            scientific_name: string | null;
            /** Family */
            family: string | null;
            /** Traits */
            traits: {
                [key: string]: components["schemas"]["TraitOut"];
            };
            partners: components["schemas"]["PartnersOut"] | null;
        };
        /** PlantSearchResponse */
        PlantSearchResponse: {
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Items */
            items: components["schemas"]["PlantSummary"][];
            /**
             * Filters
             * @default {}
             */
            filters: {
                [key: string]: components["schemas"]["FilterCountsOut"];
            };
        };
        /** PlantSummary */
        PlantSummary: {
            /** Taxon Id */
            taxon_id: number;
            /** Canonical Name */
            canonical_name: string;
            /** Family */
            family: string | null;
            /** Height Max M */
            height_max_m: number | null;
            /** Flowering Start Month */
            flowering_start_month: number | null;
            /** Flowering End Month */
            flowering_end_month: number | null;
            /** Flower Colour */
            flower_colour: string | null;
            /** Colour Known */
            colour_known: boolean;
            /** Bird Partners */
            bird_partners: number | null;
            /** Space M2 */
            space_m2: number | null;
            /** Fits Bed */
            fits_bed: boolean | null;
            fit: components["schemas"]["FitOut"];
        };
        /**
         * PlantingCreate
         * @description Either a species from the catalogue, or the words the user typed.
         *
         *     Both are ordinary. The catalogue holds 8,939 German species and no cultivars,
         *     so a name it cannot match is an answer rather than a mistake.
         */
        PlantingCreate: {
            /** Taxon Id */
            taxon_id?: number | null;
            /** Raw Name */
            raw_name?: string | null;
            /**
             * Quantity
             * @default 1
             */
            quantity: number;
        };
        /** PlantingOut */
        PlantingOut: {
            /** Planting Id */
            planting_id: number;
            /** Taxon Id */
            taxon_id: number | null;
            /** Canonical Name */
            canonical_name: string | null;
            /** Raw Name */
            raw_name: string | null;
            /** Quantity */
            quantity: number;
            /** Added At */
            added_at: string;
        };
        /** PlantingVisibility */
        PlantingVisibility: {
            /** Planting Id */
            planting_id: number;
            /** Name */
            name: string;
            /** Bed Id */
            bed_id: number;
            /** Height M */
            height_m: number | null;
            /** Visible */
            visible: boolean | null;
            /** Visible From M */
            visible_from_m: number | null;
            /** Hidden By */
            hidden_by: number | null;
            /** Estimated */
            estimated: boolean;
        };
        /**
         * Registration
         * @description What it takes to make an account.
         *
         *     No composition rules — length and the one obvious mistake, following NIST.
         *     A rule that demands a digit and a symbol produces `Passwort1!` and a sticky
         *     note, which is worse than a long phrase.
         */
        Registration: {
            /** Username */
            username: string;
            /** Password */
            password: string;
            /** Email */
            email?: string | null;
        };
        /**
         * ScoreOut
         * @description The score with everything needed to argue about it — a score a user cannot
         *     interrogate is decoration, and this one will be trusted more than it deserves.
         */
        ScoreOut: {
            /** Score */
            score: number;
            /** By Month */
            by_month: {
                [key: string]: number;
            };
            /** By Species */
            by_species: components["schemas"]["SpeciesContributionOut"][];
            /** By Group */
            by_group: {
                [key: string]: number;
            };
            /** Plantings Total */
            plantings_total: number;
            /** Plantings Without Interaction Data */
            plantings_without_interaction_data: number;
            /** Is Empty */
            is_empty: boolean;
        };
        /** SightlinesOut */
        SightlinesOut: {
            /** Plantings */
            plantings: components["schemas"]["PlantingVisibility"][];
            /** Estimated Count */
            estimated_count: number;
        };
        /** SourceOut */
        SourceOut: {
            /** Name */
            name: string;
            /** Licence */
            licence: string;
            /** Url */
            url: string;
            /** Contributes */
            contributes: string;
        };
        /** SpeciesContributionOut */
        SpeciesContributionOut: {
            /** Taxon Id */
            taxon_id: number;
            /** Canonical Name */
            canonical_name: string;
            /** German Partners */
            german_partners: number | null;
            /** Origin */
            origin: string;
            /** Forage */
            forage: number;
            /** Months */
            months: number[];
        };
        /**
         * SpeciesInfoOut
         * @description A description and photo. `licence` and `page_url` are conditions of use,
         *     not decoration — the UI may not show the extract without them.
         */
        SpeciesInfoOut: {
            /** Title */
            title: string;
            /** Extract */
            extract: string;
            /** Thumbnail Url */
            thumbnail_url: string | null;
            /** Page Url */
            page_url: string;
            /** Language */
            language: string;
            /** Licence */
            licence: string;
        };
        /**
         * StatsOut
         * @description What the catalogue actually holds, counted rather than typed.
         *
         *     Wave 1's landing page wrote "3.087 Arten" into its HTML by hand, and it was
         *     wrong the first time the catalogue was rebuilt. A page that states a number
         *     is making a claim.
         */
        StatsOut: {
            /** Species */
            species: number;
            /** Species With Full Site Profile */
            species_with_full_site_profile: number;
            /** Animal Partnerships */
            animal_partnerships: number;
            /** German Animals */
            german_animals: number;
            /** German Names */
            german_names: number;
            /** Sources */
            sources: components["schemas"]["SourceOut"][];
        };
        /**
         * TimelineOut
         * @description The bloom year. `plantings_without_interaction_data` is reported so a
         *     timeline built mostly on unknowns is visible rather than merely optimistic.
         */
        TimelineOut: {
            /** Mode */
            mode: string;
            /** Months */
            months: components["schemas"]["MonthOut"][];
            /** Gaps */
            gaps: components["schemas"]["GapOut"][];
            /** Plantings Total */
            plantings_total: number;
            /** Plantings Without Interaction Data */
            plantings_without_interaction_data: number;
            /** Is Empty */
            is_empty: boolean;
        };
        /** TraitOut */
        TraitOut: {
            /** Value */
            value: number | string | null;
            /** Unit */
            unit?: string | null;
            /** Source */
            source: string;
            /** License */
            license: string;
            /** Alternatives */
            alternatives?: {
                [key: string]: unknown;
            }[];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * ViewpointIn
         * @description Where somebody is standing, in garden metres.
         */
        ViewpointIn: {
            /** X */
            x: number;
            /** Y */
            y: number;
            /**
             * Eye Height M
             * @default 1.6
             */
            eye_height_m: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    search_plants_api_v1_plants_get: {
        parameters: {
            query?: {
                light?: number | null;
                moisture?: number | null;
                nutrients?: number | null;
                reaction?: number | null;
                temperature?: number | null;
                height_min?: number | null;
                height_max?: number | null;
                flowering_month?: number | null;
                growth_form?: components["schemas"]["GrowthForm"] | null;
                include_unknown?: boolean;
                colour?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlantSearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    plant_detail_api_v1_plants__taxon_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                taxon_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlantDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    plant_info_api_v1_plants__taxon_id__info_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                taxon_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpeciesInfoOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stats_api_v1_stats_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatsOut"];
                };
            };
        };
    };
    create_api_v1_gardens_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GardenCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GardenCreated"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_api_v1_gardens__token__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GardenOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_api_v1_gardens__token__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_bed_api_v1_gardens__token__beds_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BedCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GardenOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_obstacle_api_v1_gardens__token__obstacles_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ObstacleCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GardenOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    recompute_api_v1_gardens__token__recompute_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GardenOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    edit_bed_api_v1_gardens__token__beds__bed_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
                bed_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BedUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GardenOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    edit_obstacle_api_v1_gardens__token__obstacles__obstacle_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
                obstacle_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ObstacleUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GardenOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    claim_api_v1_gardens__token__claim_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GardenOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_planting_api_v1_gardens__token__beds__bed_id__plantings_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
                bed_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlantingCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GardenOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_planting_api_v1_gardens__token__plantings__planting_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
                planting_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GardenOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    bed_suggestions_api_v1_gardens__token__beds__bed_id__suggestions_get: {
        parameters: {
            query?: {
                limit?: number;
                colour?: string | null;
                height_min?: number | null;
                height_max?: number | null;
                flowering_month?: number | null;
                growth_form?: components["schemas"]["GrowthForm"] | null;
                include_unknown?: boolean;
                include_trees?: boolean;
                include_introduced?: boolean;
                exclude_planted?: boolean;
            };
            header?: never;
            path: {
                token: string;
                bed_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BedSuggestions"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    timeline_api_v1_gardens__token__timeline_get: {
        parameters: {
            query?: {
                forage?: boolean;
            };
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TimelineOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    score_api_v1_gardens__token__score_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScoreOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    improvements_api_v1_gardens__token__improvements_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImprovementsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    bloom_api_v1_gardens__token__bloom_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BloomPalette"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sightlines_api_v1_gardens__token__sightlines_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ViewpointIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SightlinesOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    find_place_api_v1_geo_search_get: {
        parameters: {
            query?: {
                q?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlaceSearchOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    imagery_at_api_v1_geo_imagery_get: {
        parameters: {
            query: {
                lat: number;
                lon: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImageryOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    garden_from_map_api_v1_gardens_from_map_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MapSelection"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MapGardenOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    register_api_v1_accounts_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Registration"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    log_in_api_v1_sessions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Credentials"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    log_out_api_v1_sessions_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me_api_v1_accounts_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountOut"];
                };
            };
        };
    };
    my_gardens_api_v1_accounts_me_gardens_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OwnedGardens"];
                };
            };
        };
    };
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
